version: "3.9"

services:
  dgm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dgm-lang
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
